export const DOWNLOADED_ICONS = {
    'link': require('../images/token-icons/link.png'),
    'usdt': require('../images/token-icons/usdt.png'),
    'sushi': require('../images/token-icons/sushi.png'),
    'dai': require('../images/token-icons/dai.png'),
    'aave': require('../images/token-icons/aave.png'),
    'uni': require('../images/token-icons/uni.png'),
    'yfi': require('../images/token-icons/yfi.png'),
    'auto': require('../images/token-icons/auto.png'),
    'busd': require('../images/token-icons/busd.png'),
    'egg': require('../images/token-icons/egg.png'),
    'btcb': require('../images/token-icons/btc.svg'),
    'vai': require('../images/token-icons/vai.png'),
    'dodo': require('../images/token-icons/dodo.png'),
    'comp': require('../images/token-icons/comp.png'),
    'alpha': require('../images/token-icons/alpha.png'),
    'band': require('../images/token-icons/band.png'),
    'sxp': require('../images/token-icons/sxp.png'),
    'ust': require('../images/token-icons/ust.png'),
    'inj': require('../images/token-icons/inj.png'),
    'reef': require('../images/token-icons/reef.png'),
    'front': require('../images/token-icons/front.png'),
    'lit': require('../images/token-icons/lit.png'),
    'lina': require('../images/token-icons/lina.png'),
    'zee': require('../images/token-icons/zee.jpg'),
    'bel': require('../images/token-icons/bel.png'),
    'alice': require('../images/token-icons/alice.png'),
    'dusk': require('../images/token-icons/dusk.png'),
    'trade': require('../images/token-icons/trade.png'),
    'lto': require('../images/token-icons/lto.png'),
    'lien': require('../images/token-icons/lien.png'),
    'dft': require('../images/token-icons/dft.jpg'),
    'pbtc': require('../images/token-icons/pbtc.png'),
    'gum': require('../images/token-icons/gum.png'),
    'dego': require('../images/token-icons/dego.png'),
    'xmark': require('../images/token-icons/xmark.jpg'),
    'tpt': require('../images/token-icons/tpt.png'),
    'dexe': require('../images/token-icons/dexe.png'),
    'ramp': require('../images/token-icons/ramp.png'),
    'for': require('../images/token-icons/for.png'),
    'oddz': require('../images/token-icons/oddz.png'),
    'hoo': require('../images/token-icons/hoo.png'),
    'apys': require('../images/token-icons/apys.png'),
    'bondly': require('../images/token-icons/bondly.png'),
    'arpa': require('../images/token-icons/arpa.png'),
    'fox': require('../images/token-icons/fox.png'),
    'mvi': require('../images/token-icons/mvi.png'),
    'eps': require('../images/token-icons/eps.png'),
    'jgn': require('../images/token-icons/jgn.png'),
    'tlm': require('../images/token-icons/tlm.png'),
    'perl': require('../images/token-icons/perl.png'),
    'alpa': require('../images/token-icons/alpa.png'),
    'suter': require('../images/token-icons/suter.jpg'),
    'xed': require('../images/token-icons/xed.png'),
    'bdigg': require('../images/token-icons/bdigg.png'),
    'bbadger': require('../images/token-icons/badger.png'),
    'cgg': require('../images/token-icons/cgg.png'),
    'dfd': require('../images/token-icons/dfd.png'),
    'math': require('../images/token-icons/math.png'),
    'kun': require('../images/token-icons/kun.png'),
    'hotcross': require('../images/token-icons/hotcross.png'),
    'rfox': require('../images/token-icons/rfox.png'),
    'chr': require('../images/token-icons/chr.png'),
    'tusd': require('../images/token-icons/tusd.png'),
    'qkc': require('../images/token-icons/qkc.png'),
    'usdc': require('../images/token-icons/usdc.png'),
    'woo': require('../images/token-icons/woo.png'),
    'ata': require('../images/token-icons/ata.png'),
    'mx': require('../images/token-icons/mx.png'),
    'mdx': require('../images/token-icons/mdx.png'),
    'alusd': require('../images/token-icons/alusd.png'),
    'alcx': require('../images/token-icons/alcx.png'),
    'time': require('../images/token-icons/time.png'),
    'pool': require('../images/token-icons/pool.png'),
    '3crv': require('../images/token-icons/3crv.png'),
    'cvx': require('../images/token-icons/cvx.png'),
    'cvxcrv': require('../images/token-icons/cvxcrv.png'),
    'crv': require('../images/token-icons/crv.png'),
    'susd': require('../images/token-icons/susd.png'),
    'snx': require('../images/token-icons/snx.png'),
    'uma': require('../images/token-icons/uma.png'),
    'ren': require('../images/token-icons/ren.png'),
    'xsushi': require('../images/token-icons/xsushi.png'),
    'cream': require('../images/token-icons/cream.png'),
    'hegic': require('../images/token-icons/hegic.png'),
    'pickle': require('../images/token-icons/pickle.png'),
    'omg': require('../images/token-icons/omg.jpg'),
    'amp': require('../images/token-icons/amp.png'),
    'rari': require('../images/token-icons/rari.png'),
    'dpi': require('../images/token-icons/dpi.png'),
    'yam': require('../images/token-icons/yam.png'),
    'farm': require('../images/token-icons/farm.png'),
    'dough': require('../images/token-icons/dough.png'),
    'stake': require('../images/token-icons/stake.png'),
    'akro': require('../images/token-icons/akro.png'),
    'kp3r': require('../images/token-icons/kp3r.jpg'),
    'seen': require('../images/token-icons/seen.png'),
    'esd': require('../images/token-icons/esd.png'),
    'cvp': require('../images/token-icons/cvp.png'),
    'yeti': require('../images/token-icons/yeti.png'),
    'arch': require('../images/token-icons/arch.png'),
    'badger': require('../images/token-icons/badger.png'),
    'index': require('../images/token-icons/index.png'),
    'jrt': require('../images/token-icons/jrt.png'),
    'ichi': require('../images/token-icons/ichi.png'),
    'ypie': require('../images/token-icons/ypie.png'),
    'mph': require('../images/token-icons/mph.png'),
    'tru': require('../images/token-icons/tru.png'),
    'creth2': require('../images/token-icons/creth2.png'),
    'dusd': require('../images/token-icons/dusd.png'),
    'ant': require('../images/token-icons/ant.png'),
    'cover': require('../images/token-icons/cover.png'),
    'digg': require('../images/token-icons/digg.png'),
    'nftx': require('../images/token-icons/nftx.png'),
    'api3': require('../images/token-icons/api3.png'),
    'ldo': require('../images/token-icons/ldo.png'),
    'aleph': require('../images/token-icons/aleph.png'),
    'mta': require('../images/token-icons/mta.png'),
    'rgt': require('../images/token-icons/rgt.png'),
    'idle': require('../images/token-icons/idle.png'),
    'sdt': require('../images/token-icons/sdt.png'),
    'armor': require('../images/token-icons/armor.png'),
    'rendoge': require('../images/token-icons/rendoge.png'),
    'torn': require('../images/token-icons/torn.png'),
    'vsp': require('../images/token-icons/vsp.png'),
    'dao': require('../images/token-icons/dao.png'),
    'grt': require('../images/token-icons/grt.png'),
    'ftm': require('../images/token-icons/ftm.png'),
    'punk-female': require('../images/token-icons/punk-female.png'),
    'xft': require('../images/token-icons/xft.png'),
    'zrx': require('../images/token-icons/zrx.png'),
    'deri': require('../images/token-icons/deri.png'),
    'bank': require('../images/token-icons/bank.png'),
    'perp': require('../images/token-icons/perp.png'),
    'rlc': require('../images/token-icons/rlc.png'),
    'yla': require('../images/token-icons/yla.png'),
    'punk-basic': require('../images/token-icons/punk-basic.png'),
    'mask': require('../images/token-icons/mask.png'),
    'rook': require('../images/token-icons/rook.png'),
    'dfx': require('../images/token-icons/dfx.png'),
    'inv': require('../images/token-icons/inv.jpg'),
    'ocean': require('../images/token-icons/ocean.png'),
    'dnt': require('../images/token-icons/dnt.png'),
    'aergo': require('../images/token-icons/aergo.png'),
    'egt': require('../images/token-icons/egt.png'),
    'must': require('../images/token-icons/must.png'),
    'ohm': require('../images/token-icons/ohm.png'),
    'yld': require('../images/token-icons/yld.png'),
    'bzrx': require('../images/token-icons/bzrx.png'),
    'yvboost': require('../images/token-icons/yvboost.png'),
    'axs': require('../images/token-icons/axs.png'),
    'bdi': require('../images/token-icons/bdi.png'),
    'bask': require('../images/token-icons/bask.png'),
    'btc2x-fli': require('../images/token-icons/btc2x-fli.png'),
    'ibbtc': require('../images/token-icons/ibbtc.png'),
    'zig': require('../images/token-icons/zig.png'),
    'mm': require('../images/token-icons/mm.png'),
    'pendle': require('../images/token-icons/pendle.png'),
    'civ': require('../images/token-icons/civ.png'),
    'ryoshi': require('../images/token-icons/ryoshi.png'),
    'starl': require('../images/token-icons/starl.png'),
    'ufo': require('../images/token-icons/ufo.png'),
    'f9': require('../images/token-icons/f9.png'),
    'bone': require('../images/token-icons/bone.png'),
    'leash': require('../images/token-icons/leash.png'),
    'vxv': require('../images/token-icons/vxv.png'),
    'elon': require('../images/token-icons/elon.png'),
    'meme': require('../images/token-icons/meme.png'),
    'xfund': require('../images/token-icons/xfund.png'),
    'bayc': require('../images/token-icons/bayc.png'),
    'meeb': require('../images/token-icons/meeb.png'),
    'vite': require('../images/token-icons/vite.png'),
    'uwu': require('../images/token-icons/uwu.png'),
    'wizard': require('../images/token-icons/wizard.png'),
    'cool': require('../images/token-icons/cool.png'),
    'punk': require('../images/token-icons/punk.png'),
    'pudgy': require('../images/token-icons/pudgy.png'),
    'purr': require('../images/token-icons/purr.png'),
    'avastr': require('../images/token-icons/avastr.png'),
    'sqgl': require('../images/token-icons/sqgl.png'),
    'glyph': require('../images/token-icons/glyph.png'),
    'kae': require('../images/token-icons/kae.png'),
    'revv': require('../images/token-icons/revv.png'),
    'bmi': require('../images/token-icons/bmi.png'),
    'renfil': require('../images/token-icons/renfil.png'),
    'data': require('../images/token-icons/data.png'),
    'bgld': require('../images/token-icons/bgld.png'),
    'agld': require('../images/token-icons/agld.png'),
    'lusd': require('../images/token-icons/lusd.png'),
    'nfd': require('../images/token-icons/nfd.png'),
    'id': require('../images/token-icons/id.png'),
    'slp': require('../images/token-icons/slp.png'),
    'vusd': require('../images/token-icons/vusd.png'),
    'eden': require('../images/token-icons/eden.png'),
    'tower': require('../images/token-icons/tower.png'),
    'ibeur': require('../images/token-icons/ibeur.png'),
    'onx': require('../images/token-icons/onx.png'),
    'dvf': require('../images/token-icons/dvf.png'),
    'lev': require('../images/token-icons/lev.png'),
    'premia': require('../images/token-icons/premia.png'),
    'aethc': require('../images/token-icons/aethc.png'),
    'ankr': require('../images/token-icons/ankr.png'),
    'gno': require('../images/token-icons/gno.png'),
    'ddx': require('../images/token-icons/ddx.png'),
    'bcp': require('../images/token-icons/bcp.png'),
    'bor': require('../images/token-icons/bor.png'),
    'pnk': require('../images/token-icons/pnk.png'),
    'mars4': require('../images/token-icons/mars4.png'),
    'apw': require('../images/token-icons/apw.png'),
    'banana': require('../images/token-icons/banana.png'),
    'dydx': require('../images/token-icons/dydx.png'),
    'bit': require('../images/token-icons/bit.png'),
    'wncg': require('../images/token-icons/wncg.png'),
    'wsteth': require('../images/token-icons/wsteth.png'),
    'toke': require('../images/token-icons/toke.png'),
    'bios': require('../images/token-icons/bios.png'),
    'si': require('../images/token-icons/si.png'),
    'ygg': require('../images/token-icons/ygg.png'),
    'pmon': require('../images/token-icons/pmon.png'),
    'mana': require('../images/token-icons/mana.png'),
    'wasabi': require('../images/token-icons/wasabi.png'),
    'drc': require('../images/token-icons/drc.png'),
    'ilv': require('../images/token-icons/ilv.png'),
    'blo': require('../images/token-icons/blo.png'),
    'woofy': require('../images/token-icons/woofy.png'),
    'naos': require('../images/token-icons/naos.png'),
    'umb': require('../images/token-icons/umb.png'),
    'move': require('../images/token-icons/move.png'),
    'mln': require('../images/token-icons/mln.png'),
    'ruler': require('../images/token-icons/ruler.png'),
    'bpt': require('../images/token-icons/bpt.png'),
    'sak3': require('../images/token-icons/sak3.png'),
    'bond': require('../images/token-icons/bond.png'),
    'fold': require('../images/token-icons/fold.png'),
    'ndx': require('../images/token-icons/ndx.png'),
    'degen': require('../images/token-icons/degen.png'),
    'cqt': require('../images/token-icons/cqt.png'),
    'ice': require('../images/token-icons/ice.png'),
    'renbtc': require('../images/token-icons/renbtc.png'),
    'renzec': require('../images/token-icons/renzec.png'),
    'renbch': require('../images/token-icons/renbch.png'),
    'frax': require('../images/token-icons/frax.png'),
    'fxs': require('../images/token-icons/fxs.png'),
    'any': require('../images/token-icons/any.png'),
    'scream': require('../images/token-icons/scream.png'),
    'treeb': require('../images/token-icons/treeb.png'),
    'kek': require('../images/token-icons/kek.png'),
    'shade': require('../images/token-icons/shade.png'),
    'foo': require('../images/token-icons/foo.png'),
    'steak': require('../images/token-icons/steak.png'),
    'spell': require('../images/token-icons/spell.png'),
    'just': require('../images/token-icons/just.png'),
    'ginspirit': require('../images/token-icons/ginspirit.png'),
    'lqdr': require('../images/token-icons/lqdr.png'),
    'ele': require('../images/token-icons/ele.png'),
    'grim': require('../images/token-icons/grim.png'),
    'papr': require('../images/token-icons/papr.png'),
    'rndm': require('../images/token-icons/rndm.png'),
    'yak': require('../images/token-icons/yak.png'),
    'myak': require('../images/token-icons/yak.png'),
    'snob': require('../images/token-icons/snob.png'),
    'pefi': require('../images/token-icons/pefi.png'),
    'vso': require('../images/token-icons/vso.png'),
    'xava': require('../images/token-icons/xava.png'),
    'spore': require('../images/token-icons/spore.png'),
    'tryb': require('../images/token-icons/tryb.png'),
    'sherpa': require('../images/token-icons/sherpa.png'),
    'joe': require('../images/token-icons/joe.png'),
    'teddy': require('../images/token-icons/teddy.png'),
    'tsd': require('../images/token-icons/tsd.png'),
    'klo': require('../images/token-icons/klo.png'),
    'chart': require('../images/token-icons/chart.png'),
    'relay': require('../images/token-icons/relay.png'),
    'mimatic': require('../images/token-icons/mimatic.png'),
    'gb': require('../images/token-icons/gb.png'),
    'syn': require('../images/token-icons/syn.png'),
    'qi': require('../images/token-icons/qi.png'),
    'xjoe': require('../images/token-icons/xjoe.png'),
    'wet': require('../images/token-icons/wet.png'),
    'husky': require('../images/token-icons/husky.png'),
    'elk': require('../images/token-icons/elk.png'),
    'hcfx': require('../images/token-icons/hcfx.png'),
    'hbelt': require('../images/token-icons/hbelt.png'),
    'dmt': require('../images/token-icons/dmt.png'),
    'nt': require('../images/token-icons/nt.svg'),
    'wmatic': require('../images/token-icons/wmatic.png'),
    'polybunny': require('../images/token-icons/polybunny.png'),
    'ghst': require('../images/token-icons/ghst.png'),
    'combo': require('../images/token-icons/combo.png'),
    'bitb': require('../images/token-icons/bitb.jpg'),
    'gton': require('../images/token-icons/gton.png'),
    'mim': require('../images/token-icons/mim.png'),
    'bifi': require('../images/token-icons/bifi.png'),
    'hbtc': require('../images/token-icons/hbtc.png'),
    'husd': require('../images/token-icons/husd.png'),
    'hltc': require('../images/token-icons/hltc.png'),
    'hbch': require('../images/token-icons/hbch.png'),
    'hdot': require('../images/token-icons/hdot.png'),
    'hfil': require('../images/token-icons/hfil.png'),
    'ht': require('../images/token-icons/ht.png'),
    'bal': require('../images/token-icons/bal.png'),
    'mkr': require('../images/token-icons/mkr.png'),
    'bee': require('../images/token-icons/bee.jpg'),
    'can': require('../images/token-icons/can.png'),
    'hgt': require('../images/token-icons/hgt.png'),
    'con': require('../images/token-icons/_con.png'),
    'dep': require('../images/token-icons/dep.png'),
    'edc': require('../images/token-icons/edc.png'),
    'fei': require('../images/token-icons/fei.png'),
    'tribe': require('../images/token-icons/tribe.png'),
    'shib': require('../images/token-icons/shib.png'),
    'black': require('../images/token-icons/black.png'),
    'war': require('../images/token-icons/war.png'),
    'lion': require('../images/token-icons/lion.png'),
    'cow': require('../images/token-icons/cow.png'),
    'o3': require('../images/token-icons/o3.png'),
    'wfil': require('../images/token-icons/wfil.png'),
    'dht': require('../images/token-icons/dht.png'),
    'dtop': require('../images/token-icons/dtop.png'),
    'quick': require('../images/token-icons/quick.png'),
    'wise': require('../images/token-icons/wise.png'),
    'aga': require('../images/token-icons/aga.png'),
    'agar': require('../images/token-icons/agar.png'),
    'sx': require('../images/token-icons/sx.png'),
    'cel': require('../images/token-icons/cel.png'),
    'defi5': require('../images/token-icons/defi5.png'),
    '4belt': require('../images/token-icons/4belt.png'),
    'Bitcoin-BTC': require('../images/token-icons/Bitcoin-BTC.svg'),
    'ada': require('../images/token-icons/ada.png'),
    'addy': require('../images/token-icons/addy.png'),
    'atom': require('../images/token-icons/atom.png'),
    'aurora': require('../images/token-icons/aurora.png'),
    'avax': require('../images/token-icons/avax.png'),
    'bbtc': require('../images/token-icons/bbtc.png'),
    'bcfx': require('../images/token-icons/bcfx.png'),
    'bch': require('../images/token-icons/bch.png'),
    'belt': require('../images/token-icons/belt.png'),
    'beth': require('../images/token-icons/beth.png'),
    'bgov': require('../images/token-icons/bgov.png'),
    'bmxx': require('../images/token-icons/bmxx.png'),
    'bnb': require('../images/token-icons/bnb.svg'),
    'boo': require('../images/token-icons/boo.png'),
    'broobee': require('../images/token-icons/broobee.png'),
    'bry': require('../images/token-icons/bry.png'),
    'bscx': require('../images/token-icons/bscx.png'),
    'btc': require('../images/token-icons/btc.svg'),
    'btcst': require('../images/token-icons/btcst.png'),
    'btt': require('../images/token-icons/btt.png'),
    'bux': require('../images/token-icons/bux.png'),
    'bxh': require('../images/token-icons/bxh.png'),
    'cake': require('../images/token-icons/cake.png'),
    'cos': require('../images/token-icons/cos.png'),
    'ctk': require('../images/token-icons/ctk.png'),
    'ditto': require('../images/token-icons/ditto.png'),
    'dog': require('../images/token-icons/dog.png'),
    'doge': require('../images/token-icons/doge.png'),
    'dot': require('../images/token-icons/dot.png'),
    'eos': require('../images/token-icons/eos.png'),
    'eth': require('../images/token-icons/eth.svg'),
    'fil': require('../images/token-icons/fil.png'),
    'filda': require('../images/token-icons/filda.png'),
    'hakka': require('../images/token-icons/hakka.png'),
    'hawk': require('../images/token-icons/hawk.svg'),
    'helmet': require('../images/token-icons/helmet.png'),
    'hfi': require('../images/token-icons/hfi.png'),
    'hpt': require('../images/token-icons/hpt.png'),
    'htmoon': require('../images/token-icons/htmoon.png'),
    'hzn': require('../images/token-icons/hzn.png'),
    'itam': require('../images/token-icons/itam.png'),
    'lhb': require('../images/token-icons/lhb.png'),
    'lmt': require('../images/token-icons/lmt.png'),
    'ltc': require('../images/token-icons/ltc.png'),
    'matic': require('../images/token-icons/matic.svg'),
    'mausdc': require('../images/token-icons/mausdc.svg'),
    'mbox': require('../images/token-icons/mbox.png'),
    'nrv': require('../images/token-icons/nrv.png'),
    'nuls': require('../images/token-icons/nuls.png'),
    'ori': require('../images/token-icons/ori.png'),
    'pauto': require('../images/token-icons/pauto.png'),
    'pcws': require('../images/token-icons/pcws.png'),
    'pipi': require('../images/token-icons/pipi.png'),
    'ptd': require('../images/token-icons/ptd.png'),
    'sfp': require('../images/token-icons/sfp.png'),
    'slnv2': require('../images/token-icons/slnv2.png'),
    'sovi': require('../images/token-icons/sovi.png'),
    'spirit': require('../images/token-icons/spirit.png'),
    'swingby': require('../images/token-icons/swingby.png'),
    'swth': require('../images/token-icons/swth.png'),
    'tko': require('../images/token-icons/tko.png'),
    'trx': require('../images/token-icons/trx.png'),
    'twt': require('../images/token-icons/twt.png'),
    'vrt': require('../images/token-icons/vrt.png'),
    'watch': require('../images/token-icons/watch.png'),
    'wht': require('../images/token-icons/wht.png'),
    'win': require('../images/token-icons/win.png'),
    'xrp': require('../images/token-icons/xrp.png'),
    'xvs': require('../images/token-icons/xvs.png'),
    'zil': require('../images/token-icons/zil.png'),
    'τBTC': require('../images/token-icons/τbtc.png'),
    'png': require('../images/token-icons/png.png'),
    'wavax': require('../images/token-icons/wavax.png'),
    'fusdt': require('../images/token-icons/fusdt.png'),
    'a3crv' : require('../images/token-icons/a3crv.png'),
    'crvbusd' : require('../images/token-icons/crvbusd.png'),
    'crveurs' : require('../images/token-icons/crveurs.png'),
    'crvfrax' : require('../images/token-icons/crvfrax.png'),
    'crvhbtc' : require('../images/token-icons/crvhbtc.png'),
    'crvlink' : require('../images/token-icons/crvlink.png'),
    'crvlusd' : require('../images/token-icons/crvlusd.png'),
    'crvsbtc' : require('../images/token-icons/crvsbtc.png'),
    'crvsteth' : require('../images/token-icons/crvsteth.png'),
    'crvtricrypto' : require('../images/token-icons/crvtricrypto.png'),
    'crvusdn' : require('../images/token-icons/crvusdn.png'),
    'crvusdp' : require('../images/token-icons/crvusdp.png'),
    'curvalusd' : require('../images/token-icons/curvalusd.png'),
    'eswap' : require('../images/token-icons/eswap.png'),
    'crvrenwbtc' : require('../images/token-icons/crvrenwbtc.png'),
    'zoo' : require('../images/token-icons/zoo.png'),
    'crvbbtc' : require('../images/token-icons/crvbbtc.png'),
    'crvsaave' : require('../images/token-icons/crvsaave.png'),
    'crvsusd' : require('../images/token-icons/crvsusd.png'),
    'crvobtc' : require('../images/token-icons/crvobtc.png'),
    'crvpbtc' : require('../images/token-icons/crvpbtc.png'),
    'crvtbtc' : require('../images/token-icons/crvtbtc.png'),
    'crvdusd' : require('../images/token-icons/crvdusd.png'),
    'ycrv' : require('../images/token-icons/ycrv.png'),
    'crvaethc' : require('../images/token-icons/crvaethc.png'),
    'crvreth' : require('../images/token-icons/crvreth.png'),
    'crvust' : require('../images/token-icons/crvust.png'),
    'crvybusd' : require('../images/token-icons/crvybusd.png'),
    'crvtusd' : require('../images/token-icons/crvtusd.png'),
    'crvgusd' : require('../images/token-icons/crvgusd.png'),
    'crvmusd' : require('../images/token-icons/crvmusd.png'),
    'crvhusd' : require('../images/token-icons/crvhusd.png'),
    'crvpax' : require('../images/token-icons/crvpax.png'),
    'crvusdk' : require('../images/token-icons/crvusdk.png'),
    'crvrsv' : require('../images/token-icons/crvrsv.png'),
    'vwbtc' : require('../images/token-icons/vwbtc.svg'),
    'vusdc' : require('../images/token-icons/vusdc.svg'),
    'veth' : require('../images/token-icons/veth.svg'),
    'vlink' : require('../images/token-icons/vlink.svg'),
    'ibethv2' : require('../images/token-icons/ibethv2.png'),
    'yusd' : require('../images/token-icons/yusd.png'),
    'near' : require('../images/token-icons/near.png'),
    'scrt' : require('../images/token-icons/scrt.png'),
    'usdp' : require('../images/token-icons/usdp.png'),
    'duck' : require('../images/token-icons/duck.png'),
    '$dg' : require('../images/token-icons/$dg.png'),
    '$trdl' : require('../images/token-icons/$trdl.png'),
    'pont' : require('../images/token-icons/pont.png'),
    'pwing' : require('../images/token-icons/pwing.png'),
    'crvusdt' : require('../images/token-icons/crvusdt.png'),
    'crvcomp' : require('../images/token-icons/crvcomp.png'),
    'crvib' : require('../images/token-icons/crvib.png'),
    'crvseth' : require('../images/token-icons/crvseth.png'),
    'saddlealeth' : require('../images/token-icons/saddlealeth.svg'),
    '1one' : require('../images/token-icons/1one.png'),
    'beltbtc': require('../images/token-icons/beltbtc.png'),
    'belteth': require('../images/token-icons/belteth.png'),
    'beltbnb': require('../images/token-icons/beltbnb.png'),
    'titan': require('../images/token-icons/titan.png'),
    'bscpad': require('../images/token-icons/bscpad.png'),
    'alpaca': require('../images/token-icons/alpaca.png'),
    'c98': require('../images/token-icons/c98.png'),
    'one': require('../images/token-icons/one.png'),
    'skill': require('../images/token-icons/skill.png'),
    'chess': require('../images/token-icons/chess.png'),
}
